### ISSUE TITLE
DK atlas regions

### ISSUE THREAD

**Issue by Melissa1909** [alegiac95/Imaging-transcriptomics#10]
Dear alegiac95,

thanks for providing the scripts! I have just gone through the paper and description of this GitHub repo and I want to adapt your software to my project. However, I use the typical implementation of the DK from Freesurfer with 34 cortical DK ROIs instead of the 41 ROIs that you have used and, if I'm not mistaken, 41 ROIs are required to implement the script as ist is. Is it possible to change the input to other cortical parcellations as well (i.e., DK-34)?

Cheers,
Melissa

**Comment by alegiac95** [comment]
Hi Melissa,
Theoretically you can do it, just there are some bits you need to change especially where the data get reshaped (e.g., `.reshape(41,1)` , which unfortunately i did some times).

Keep in mind that the first 34 regions of the atlas we use are the cortical regions while the remaining are the subcortical (only for the left hemisphere).  So an option worth exploring would be to force the elements corresponding to the subcortical regions to 0 (you can do this importing the library in a python script). This would not generate any error from the software but I'm not entirely sure if the results are correct.

**Comment by alegiac95** [comment]
Hi @Melissa1909, I wanted to let you know that we are planning to release sometimes before the end of next week a new version that will run allow to run only on the cortical regions (i.e., dk34 regions) as well as cortical and subcortical together. We are running some more tests but this should take care of the original question you proposed.
