### ISSUE TITLE
pip installation can not resolve enigmatoolbox dependencies

### ISSUE THREAD

**Issue by YCHuang0610** [alegiac95/Imaging-transcriptomics#15]
After 
`pip install -e git+https://github.com/netneurolab/pypyls.git/#egg=pyls`
and
`pip install imaging-transcriptomics`
in a new conda environment with Python=3.8, an error was occurred when import imaging-transcriptomics package that it can't find the module named enigmatoolbox.
I figured out that the enigmatoolbox package seems can not be resolve by pip installation automatically, so I have to install the enigmatoolbox package from Github manually, with the code bellow according to the document of enigmatoolbox:
```
git clone https://github.com/MICA-MNI/ENIGMA.git
cd ENIGMA
python setup.py install
```

**Comment by alegiac95** [comment]
Hi @YCHuang0610, 
yes, the `enigmatoolbox` needs to be installed manually using the method you have used, since it cant be installed using `pip`. 
Is the issue persistent after you installed it as you did?

**Comment by alegiac95** [comment]
Can I ask you to try and see whether you can import the toolbox in an interactive shell without errors? For example by running in a terminal:
`python` and after the interactive shell has opened by typing `import enigmatoolbox`?

**Comment by YCHuang0610** [comment]
Thanks for the reply, it was solved after manually installed enigmatoolbox. I suggest add this issue to the readme document in case the install error happens.

**Comment by alegiac95** [comment]
Hi thanks for the suggestion @YCHuang0610, I've updated the `readthedocs` page but totally forgot about the README.md

Thanks!
